import { useState, useEffect } from "react";
import SoftBackdrop from "../components/SoftBackdrop";
import { Sparkles, ArrowRight, BarChart3 } from "lucide-react";
import { dummyThumbnails } from "../assets/assets";

const Community = () => {
    const [thumbnails, setThumbnails] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);

    const featuredThumbnails = dummyThumbnails.slice(0, 4).map((thumb, index) => ({
        ...thumb,
        imageUrl: thumb.image_url || thumb.image_url,
        ctrScore: [9.1, 8.4, 7.9, 9.7][index] ?? 8.5,
        _id: thumb._id || `asset-${index}`,
    }));

    useEffect(() => {
        fetchThumbnails();
    }, []);

    const fetchThumbnails = async () => {
            try {
                const response = await fetch('http://localhost:5000/api/thumbnails/community');
                const result = await response.json();
                if (result.success) {
                    setThumbnails(result.data);
                }
            } catch (error) {
                console.error("Error fetching community thumbnails:", error);
            } finally {
                setLoading(false);
            }
        };

    const displayedThumbnails = [...featuredThumbnails, ...thumbnails];

    return (
        <>
            <SoftBackdrop />
            <div className="pt-24 min-h-screen">
                <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
                    <div className="text-center mb-16 space-y-4">
                        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10 text-xs font-medium text-zinc-400">
                            <Sparkles className="size-3 text-pink-500" />
                            <span>Community Gallery</span>
                        </div>
                        <h1 className="text-4xl md:text-5xl font-bold text-white tracking-tight">
                            Generated by the <span className="bg-gradient-to-r from-pink-500 to-purple-500 bg-clip-text text-transparent">Thumblify</span> Community
                        </h1>
                        <p className="text-zinc-400 max-w-2xl mx-auto text-lg">
                            Explore trending thumbnails and get inspired by what others are creating.
                        </p>
                    </div>

                    {loading ? (
                        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
                            {[1, 2, 3, 4, 5, 6].map((idx) => (
                                <div key={idx} className="aspect-video rounded-2xl bg-white/5 animate-pulse border border-white/10" />
                            ))}
                        </div>
                    ) : (
                        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
                            {displayedThumbnails.map((thumb) => (
                                <div key={thumb._id} className="group relative rounded-2xl overflow-hidden border border-white/10 bg-white/5 hover:border-white/20 transition-all duration-300">
                                    <div className="aspect-video overflow-hidden">
                                        <img 
                                            src={thumb.imageUrl || thumb.image_url} 
                                            alt={thumb.title} 
                                            className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
                                        />
                                    </div>
                                    <div className="p-5 space-y-3">
                                        <h3 className="text-lg font-semibold text-white line-clamp-1">{thumb.title}</h3>
                                        <div className="flex items-center justify-between">
                                            <div className="flex items-center gap-2 text-emerald-400">
                                                <BarChart3 className="size-4" />
                                                <span className="text-sm font-bold">{thumb.ctrScore ?? 8.2}% CTR</span>
                                            </div>
                                            <button className="text-zinc-400 group-hover:text-white transition-colors">
                                                <ArrowRight className="size-5" />
                                            </button>
                                        </div>
                                    </div>
                                    <div className="absolute top-3 left-3 px-2 py-1 rounded-md bg-black/60 backdrop-blur-md text-[10px] font-bold text-white/80 uppercase tracking-widest border border-white/10">
                                        {thumb.style}
                                    </div>
                                </div>
                            ))}
                        </div>
                    )}

                    {!loading && thumbnails.length === 0 && (
                        <div className="text-center py-20">
                            <p className="text-zinc-500">No thumbnails available yet. Be the first to generate one!</p>
                        </div>
                    )}
                </main>
            </div>
        </>
    );
};

export default Community;
